### ISSUE TITLE
Please help to fix the github URL for the datamesh-workflow repo. It is pointing to the AWS internal repo.

### ISSUE THREAD

**Issue by thanhdatle** [aws-samples/aws-lakeformation-datasharing-workflow#3]
Hi @jmgtan , I noticed the github URL for the datamesh-workflow repo is pointing to the AWS internal repo.

`You can clone the workflow UI and AWS CDK scripts from the [GitHub repository](https://gitlab.aws.dev/jantan/datamesh-workflow).`

Could you help to fix this please?

**Comment by jmgtan** [comment]
Thanks, I just fixed it now.
